#!/usr/bin/ruby
require 'securerandom'
file = File.new("variables.pp", "r")
while(line = file.gets)
        File.open("variables.pp.new", 'a') {|f| f.write(line.gsub("#RANDOM_STRING",SecureRandom.hex)) }

