#!/usr/bin/ruby
require 'securerandom'
file = File.new("variables.pp", "r")

def random_password(size = 16)
  chars = (('a'..'z').to_a + ('A'..'Z').to_a + ('0'..'9').to_a + ['!','#','%','&','=','?','+','-']) - %w(i o 0 1 l 0)
  (1..size).collect{|a| chars[rand(chars.size)] }.join
end

while(line = file.gets)
        File.open("variables.pp.new", 'a') {|f| f.write(line.gsub("#RANDOM_STRING",random_password())) }
end


