#!/sbin/sh

. /lib/svc/share/smf_include.sh

search=`svcprop -p options/search $SMF_FMRI`
domain=`svcprop -p options/domain $SMF_FMRI`
nameserver=`svcprop -p options/nameserver $SMF_FMRI`

case "$1" in
    "start")
        mv -f  /etc/resolv.conf /etc/resolv.conf.backup

        if [ "$search" != '""' ]
        then
                echo "search $search" >> /etc/resolv.conf
        fi

        if [ "$domain" != '""' ]
        then
                echo "domain $domain" >> /etc/resolv.conf
        fi

        if [ "$nameserver" != '""' ]
        then
                echo "nameserver $nameserver" >> /etc/resolv.conf
        fi

        ;;

    "stop")
	mv -f  /etc/resolv.conf.backup /etc/resolv.conf
        ;;

    *)
        echo "Usage: $0 { start | stop }"
        exit $SMF_EXIT_ERR_CONFIG
esac

exit $SMF_EXIT_OK
